### ISSUE TITLE
Create Base Android Application

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#1]
### Description:
Create the android application with the web view component to be directed to our web applications.

### Tasks:
- [x] Create Web View component that will load hardcoded URL
  - https://developer.chrome.com/multidevice/webview/gettingstarted
- [x] Add permissions needed (Video, Mic, Location) to manifest to be enabled manually
### Testing:
- [x] Works with [React Demo](https://justinhergott.ca/demos/arua-stock-exchange)
- [x] Works with [Maps Demo](https://justinhergott.ca/demos/map)
- [ ] Works with [WebRTC Demo]()

**Comment by xHergz** [comment]
@kwallace0906 just need to verify the app in the repo works with web RTC and move this to done.

**Comment by xHergz** [comment]
Application ended up not working with WebRTC in an Android Web View.
