### ISSUE TITLE
Create Client Trait Tables

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#11]
### Description:
Create the tables that describe the traits of a client.
### Tasks:
- [x] Create the Hair_Colour Table
  - Hair_Colour_Id
  - Description
- [x] Fill the Hair_Colour Table with some initial data
- [x] Create the Eye_Colour Table
  - Eye_Colour_Id
  - Description
- [x] Fill the Eye_Colour Table with some initial data
- [x] Create the Skin_Tone Table
  - Skin_Tone_Id
  - Description
- [x] Fill the Skin_Tone Table with some initial data
### Tests:
N/A
