### ISSUE TITLE
Add Static Data for Client Traits

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#12]
### Description:
Get the static data for the client traits from Karistan and add it to the Data folder in the database.
### Tasks:
- [ ] Add the Hair_Colour static data
  - TBD
- [ ] Add the Eye_Colour static data
  - TBD
- [ ] Add the Skin_Tone static data
  - TBD
