### ISSUE TITLE
Create Client Preference Schema

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#13]
### Description:
Create the schema that will store the Client allergies and sensitivities information and the product preference information.
### Tasks:
- [x] Create the Client_Allergy_Sensitivity table
- [x] Create the Allergy_Sensitivity table
- [x] Add some initial information for allergy/sensitivity
- [x] Create the Client_Product_Preference table
- [x] Create the Product_Preference table
- [x] Add some initial information to the product preferences
### Tests:
N/A

**Comment by xHergz** [comment]
Blocked by #14, need it for foreign key.

**Comment by xHergz** [comment]
No longer blocked. #14 is not committed yet, doing it all in one pull request.
