### ISSUE TITLE
Add Link Tag and Manifest for "Add to homescreen"

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#130]
### Description:
Add the link tag and manifest outlined here: https://developers.google.com/web/fundamentals/native-hardware/fullscreen/#launching_a_page_fullscreen_from_home_screen to make the app more accessible when installed as a web app on the users home screen with "Add to homescreen" 
### Tasks:
- [x] Add link tag with content="yes" to open full screen
- [x] Add manifest file to show icon and name
### Tests:
- [ ] Page opens in full screen
- [ ] Homescreen app shortcut has icon
