### ISSUE TITLE
Create the Client Profile Schema

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#14]
### Description:
Create the schema that stores client profile information and client head shots in the database.
### Tasks:
- [x] Create the Client_Profile table
- [x] Create the Headshot_Type table
- [x] Add some initial data to the Headshot_Type table (Front, Left Side, Right Side)
- [x] Create the Client_Headshot table
### Tests:
N/A

**Comment by xHergz** [comment]
Block by #11, need those tables for FK references.

**Comment by xHergz** [comment]
No longer blocked, starting development.

**Comment by xHergz** [comment]
Changing Client_Headshot_Type to Headshot_Type

**Comment by xHergz** [comment]
Diverting the stored procs to the backend issues.
