### ISSUE TITLE
Create schema for Artist Applications

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#15]
### Description:
Create the schema for artist applications and storing the information received with them.
### Tasks:
- [x] Create Artist_Application table
- [x] Create the Artist_Credential table
- [x] Create the Existing_Portfolio_Link table
### Tests:
N/A

**Comment by xHergz** [comment]
Blocked by #14, needs Client_Profile table for FK reference.

**Comment by xHergz** [comment]
No longer blocked by #14
