### ISSUE TITLE
Create Schema for Service Description Tables

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#19]
### Description:
Add the schema for the Makeover Type, Service Type, and Consultation Type tables to describe the different services an Artist can provide.
### Tasks:
- [x] Create the Makeover_Type table
- [x] Add some initial data to the Makeover_Type table
  - Formal
  - Bridal
  - Glam
- [x] Create the Service_Type table
- [x] Add some initial data to the Service_Type table
  - Instant Consultation
  - ASAP Makeover
  - Future Makeover
- [x] Create the Consultation_Type table
- [x] Add some initial data to the Consultation_Type table
  - 10 minutes
  - 20 minutes
  - 30 minutes
### Tests:
N/A
