### ISSUE TITLE
Add Splash Screen to Android App

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#2]
### Description:
Add a splash screen to the android app to check for the appropriate permissions because they need to be enabled at run time on Android 6.0 and later.
### Tasks:
- [x] Create splash screen
- [x] Check for appropriate permissions (Video, Mic, Location)
### Testing:
- [x] Application requests permissions on first start on fresh install
- [x] Works with [React Demo](https://justinhergott.ca/demos/arua-stock-exchange)
- [x] Works with [Maps Demo](https://justinhergott.ca/demos/map)
- [ ] Works with [WebRTC Demo]()

**Comment by xHergz** [comment]
Apparently the splash screen grabbing the permissions is not a good practice. So, we can keep the splash screen if we want by using method 1 here: https://android.jlelse.eu/the-complete-android-splash-screen-guide-c7db82bce565 but the permissions will just be requested when the app starts for the first time, or when the user restricts permissions.

**Comment by xHergz** [comment]
@kwallace0906 same thing as #1 , verify, move to done on the project board, and close them

**Comment by xHergz** [comment]
Application ended up not working with WebRTC in an Android Web View.
