### ISSUE TITLE
Add Static Data for Service Description Tables

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#20]
### Description:
Get the data that should go in the Makeover Type, Service Type, and Consultation Type tables and add it to the Data folder for the database.
### Tasks:
- [ ] Add the static data for the Makeover_Type table
- [ ] Add the static data for the Service_Type table
- [ ] Add the static data for the Consultation_Type table
