### ISSUE TITLE
Create Schema for Artist Profile

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#21]
### Description:
Create all the tables that handle the information for Artist profiles/portfolios.
### Tasks:
- [x] Create the Artist_Portfolio table
- [x] Create the Artist_Makeover_Offered table
- [x] Create the Artist_Service table
- [x] Create the Artist_Service_Consultation table
- [x] Create the Artist_Service_Addon table
- [x] Create the Artist Qualification table
- [x] Create the Artist_Portfolio_Picture table
### Tests:
N/A

**Comment by xHergz** [comment]
Blocked by #19, needed for FK restraints.

**Comment by xHergz** [comment]
No longer blocked by #19, doing this issue in the same branch.

**Comment by xHergz** [comment]
Changing Artist_Profile to Artist_Portfolio to keep terminology separate from client profile.
