### ISSUE TITLE
Create Supporting Procedures for Artist Profile

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#22]
### Description:
Create the stored procedures that will support the tables for Artist Profiles.
### Tasks:
- [ ] Create CreateArtistProfile procedure
  - Session Key
  - Profile Picture Path
  - Biography
- [ ] Create UpdateArtistProfile procedure
  - Session Key
  - Artist Profile Id
  - Profile Picture Path
  - Biography
- [ ] Create Add Artist Qualification procedure
  - Session Key
  - Artist Profile Id
  - Year Obtained
  - Description
- [ ] Create Update Artist Qualification procedure
  - Session Key
  - Artist Qualification Id
  - Year Obtained
  - Description
- [ ] Create Remove Artist Qualification procedure
  - Session Key
  - Artist Qualification Id
- [ ] Create Add Artist Makeover Offered procedure
  - Session Key
  - Artist Profile Id
  - Makeover Type Id
- [ ] Create Remove Artist Makeover Offered procedure
  - Session Key
  - Artist Makeover Offered Id
- [ ] Create Add Portfolio Picture procedure
  - Session Key
  - Artist Profile Id
  - Image Path
  - Makeover Type Id
- [ ] Create Remove Portfolio Picture procedure
  - Session Key
  - Artist Portfolio Picture Id
- [ ] Create Add Artist Service procedure
  - Session Key
  - Artist Makeover Offered Id
  - Service Type Id
  - Base Price
- [ ] Create Update Artist Service procedure
  - Session Key
  - Artist Service Id
  - Artist Makeover Offered Id
  - Service Type Id
  - Base Price
- [ ] Create Remove Artist Service procedure (should remove all add ons and consultations)
  - Session Key
  - Artist Service Id
- [ ] Create Add Artist Service Consultation procedure
  - Session Key
  - Artist Service Id
  - Consultation Id
  - Price
- [ ] Create Update Artist Service Consultation procedure
  - Session Key
  - Artist Service Consultation Id
  - Artist Service Id
  - Consultation Id
  - Price
- [ ] Create Remove Artist Service Consultation procedure
  - Session Key
  - Artist Service Consultation Id
- [ ] Create Add Artist Service Addon procedure
  - Session Key
  - Artist Service Id
  - Description
  - Price
- [ ] Create Update Artist Service Addon procedure
  - Session Key
  - Artist Service Add On Id
  - Artist Service Id
  - Description
  - Price
- [ ] Create Remove Artist Service Addon procedure
  - Session Key
  - Artist Service Add on Id
### Tests:
- [ ] Test CreateArtistProfile procedure
- [ ] Test UpdateArtistProfile procedure
- [ ] Test Add Artist Qualification procedure
- [ ] Test Update Artist Qualification procedure
- [ ] Test Remove Artist Qualification procedure
- [ ] Test Add Artist Makeover Offered procedure
- [ ] Test Remove Artist Makeover Offered procedure
- [ ] Test Add Portfolio Picture procedure
- [ ] Test Remove Portfolio Picture procedure
- [ ] Test Add Artist Service procedure
- [ ] Test Update Artist Service procedure
- [ ] Test Remove Artist Service procedure (should remove all add ons and consultations)
- [ ] Test Add Artist Service Consultation procedure
- [ ] Test Update Artist Service Consultation procedure
- [ ] Test Remove Artist Service Consultation procedure
- [ ] Test Add Artist Service Addon procedure
- [ ] Test Update Artist Service Addon procedure
- [ ] Test Remove Artist Service Addon procedure

**Comment by xHergz** [comment]
Blocked by #21, needs schema to make procs.
