### ISSUE TITLE
Create Review Schema

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#24]
### Description:
Create the schema to hold Client and Artist reviews.
### Tasks:
- [x] Create the Artist Review table
- [x] Create the Artist Review reply table
- [x] Create the Artist Review Portfolio Link table
- [x] Create the Client Review table
### Tests:
N/A

**Comment by xHergz** [comment]
Blocked by #14, #21, #23. Needed for FK References.

**Comment by xHergz** [comment]
No longer blocked by #14, #21, and #23. Diverting stored proc to later issue.

**Comment by xHergz** [comment]
Change Artist_Review_Photo_Link to Artist_Review_Picture_Link to make things consistent.
