### ISSUE TITLE
Add Log Tables to ER Diagram

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#25]
### Description:
Add logging tables to the ER diagram for client profiles, artist profiles, artist applications, and reviews.
### Tasks:
- [ ] Add logging tables for Client Profiles
- [ ] Add logging tables for Artist Applications
- [ ] Add logging tables to Artist Profiles
- [ ] Add logging tables to Reviews

**Comment by xHergz** [comment]
Blocked by #14, #15, #16, #24. Need for FK References.
