### ISSUE TITLE
Create Login Page Backend

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#28]
### Description:
Create the backend for the login page. This includes checking an email and password against a store password hash.
### Tasks:
- [x] Add basic login page
- [x] Add stored proc to get password hash
- [x] Add DAL method to call above stored proc
- [x] Verify password with password_verify 
### Tests:
- [x] Displays an error when an email is not found
- [x] Displays an error when password is incorrect
- [x] Successfully logs in user and sets session cookie
