### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#29]
### Description:
Polish up the front end login page from the basic page used for testing the backend.
### Tasks:
- [x] Use the common header from the sign up page
- [x] Add in 2 text inputs
- [x] Login button
- [x] Sign up link
- [x] Error Displays
### Tests:
- [x] Displays real time error with invalid email
- [x] Displays front end error with empty password
- [x] Successfully logs in

**Comment by xHergz** [comment]
Blocked by #28, need backend first.

**Comment by xHergz** [comment]
No longer blocked by #28
