### ISSUE TITLE
Set up the React Code Structure

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#35]
### Description:
Set up the React app so its in a runnable state and has shell pages for each known page.
### Tasks:
- [x] Set up the Basic React App with the appropriate names/paths so it builds
- [x] Bring in the existing common components from other assignments
- [x] Make containers for each known page on the site map
