### ISSUE TITLE
Create Header and Footer for React Pages

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#37]
### Description:
Create the common Header and Footer for the React pages, place them in the main app so they are on every page, and get the session key from the cookie. This should be used to get some basic User information that will be needed for navigating to different pages from the header.
### Tasks:
- [x] Create Header with Hamburger and Navigation
- [x] Create Footer with links to privacy policyand ToS
- [x] Add action to get the cookie with session key and call new end point
- [x] Add reducer for user data
### Tests:
- [x] Header is responsive by size of window
- [x] Header hamburger opens and closes menu
- [x] Footer links work
- [x] React app displays error when no session cookie is found
- [x] React app can get session key from cookie and get user info
