### ISSUE TITLE
Create Sign Up Page

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#4]
### Description:
Create a page for people to sign up as the most basic form of user. This allows us to get their information in the application swiftly and allows them to start using the app before setting up any kind of profile.
### Tasks:
- [x] Add common header to be used by any non React pages
- [x] Add common footer to be used by any non React pages
- [x] Add input fields
  - Email
  - Password
  - Confirm Password
  - Display Name
  - First Name
  - Last Name
- [x] Add validation on the front end
  - Email: valid email address
  - Password: minimum 8 chars, max 50
  - Confirm Password: must match password
  - Display Name: only letters, numbers, -, and _
  - First Name: min 1 char, max 100
  - Last Name: min 1 char, max 100
### Testing:
- [x] Front end doesn't allow submission invalid email
- [x] Front end doesn't allow submission of invalid password, or unconfirmed
- [x] Front end doesn't allow submission of invalid display name
- [x] Front end doesn't allow submission of invalid first or last name

**Comment by xHergz** [comment]
Blocked by #6, need to determine information to collect.

**Comment by xHergz** [comment]
Updated the initial comment to the new sign up page. Now we will allow users to sign up with basic information, and enter client information later. The sign up page will no longer make them choose artist or client. Everyone will sign up as a client and then submit an application to be an artist through another portion of the app.
No longer blocked by #6
