### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#45]
### Description:
Create the first draft of the home page with tiles for some of the key actions in the app.
### Tasks:
- [x] Add tiles for key pages
  - Browse Artists
  - Instant Consult. Search
  - ASAP makeover search
  - Future Appointment Search
  - Schedule
- [x] Tiles are responsive
  - Sqaure when screen is larger, single stack when screen is smaller
### Tests:
- [x] Tiles are responsive
