### ISSUE TITLE
Create Notifications Page

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#46]
### Description:
Create the notifications page and add notification alerts to the hamburger in the header. (using set interval to keep checking)
### Tasks:
- [x] Add notification stack to page
- [x] Add actions to call API
- [x] Add little red circle to hamburger for new notifications
### Tests:
- [x] Can display notifications
- [x] Gets new notification
- [x] Acknowledges notifications when notification page is opened
