### ISSUE TITLE
Create Notification Backend

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#47]
### Description:
Add the stored procs and api end point for notifcations.
### Tasks:
- [x] Added proc to get latest notifications for user
- [x] Add proc to add notifications for user
- [x] Add proc to acknowledge notifications for user
- [x] Add api endpoint for notifications
### Tests:
- [x] API returns notifications for user
- [x] API returns 'more' notifications for user
- [x] API acknowledges notifications for user
