### ISSUE TITLE
Create Authentication Backend

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#48]
### Description:
Create the backend procs and endpoint for user authentication and info gathering.
### Tasks:
- [x] Create Stored Proc to get user info from Session Key
  - Display Name
  - IsArtist
  - First Name
  - Last Name
- [x] Implement API entry point and htaccess
- [x] Add end point for calling stored proc above
### Tests:
- [x] API Entry point with htaccess works
- [x] Proc returns info with valid, active session key
- [x] Proc returns error with unknown session key
- [x] Proc returns error with expired session key
- [x] API endpoint can parse session key from header as bearer token
- [x] API endpoint returns information from proc

**Comment by xHergz** [comment]
The PHP backend will check if the requester session key is valid like any other end point.

Stored proc needs to take in a session key as the requester, and a session key as the queried key. The proc needs to check if the queried key exists, if the requester is authorized to get info about the queried key (right now if the match), check if the session is active, check if the session is expired, and check if the user is active.

The proc will return the user display name, first name, last name, and if they are an artist.
