### ISSUE TITLE
Create Sign Up Backend

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#5]
### Description:
Create the backend methods for signing up a user.
### Tasks:
- [x] Determine Expected Fields
- [x] Add method to DAL to create user
- [x] Add method to DAL to create session
- [x] Validates all input fields
- [x] Creates user, then session with user id, then logs the creation of the user
### Testing:
- [x] Back end rejects invalid email and returns error code
  **Test Case 1**
  - Email: test
  - Password: password
  - Confirm Password: password
  - Display Name: Test
  - First Name: Test
  - Last Name: Test
- [x] Back end rejects mismatched passwords and returns error code
  **Test Case 1**
  - Email: test@email.com
  - Password: password
  - Confirm Password: asdfg
  - Display Name: Test
  - First Name: Test
  - Last Name: Test
- [x] Back end rejects too short passwords and returns error code
  **Test Case 1**
  - Email: test@email.com
  - Password: password
  - Confirm Password: asdfg
  - Display Name: Test
  - First Name: Test
  - Last Name: Test
- [x] Back end rejects invalid names and returns error code
  **Test Case 1**
  - Email: test@email.com
  - Password: password
  - Confirm Password: password
  - Display Name: Test!@#$
  - First Name: Test
  - Last Name: Test
  **Test Case 2**
  - Email: test@email.com
  - Password: password
  - Confirm Password: password
  - Display Name: Test
  - First Name: Test!@#$
  - Last Name: Test
  **Test Case 3**
  - Email: test@email.com
  - Password: password
  - Confirm Password: password
  - Display Name: Test
  - First Name: Test
  - Last Name: Test!@#$
- [x] Back end accepts valid info and returns correct error code
  **Test Case 1**
  - Email: test@email.com
  - Password: password
  - Confirm Password: password
  - Display Name: Test
  - First Name: Test
  - Last Name: Test

**Comment by xHergz** [comment]
Block by #4, need to determine what fields will be there.

**Comment by xHergz** [comment]
No longer blocked by #6. Change from end point to just back end php method as the login and sign up will be separate pages, not within the react single page app.
