### ISSUE TITLE
Accounts Page Database Procs

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#53]
### Description:
Add the stored procedures to support displaying and updating user account information in the database.
### Tasks:
- [x] Get User procedure
- [x] Update User procedure
- [x] Deactivate User procedure
### Tests:
- [x] Get User works with valid user name
- [x] Get User returns an error code when display name does not exist
- [x] Update User works with valid info
- [x] Update User returns an error code when the user id does not exist
- [x] Update User returns an error code when the email is unavailable
- [x] Update User returns an error code when the display name is unavailable
- [x] Deactivate User deactivates the user
- [x] Deactivate User returns an error code when the user id is not found
