### ISSUE TITLE
Accounts API Endpoints

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#54]
### Description:
Create the API endpoints that will be used to access, update, and deactivate user accounts.
### Tasks:
- [x] Add the get user by display name end point
- [x] Add the update user by user id end point
- [x] Add the deactivate user by id end point
### Tests:
- [x] Get user end point returns info for authorized session key (session belongs to user)
- [x] Get user end point returns unauthorized when session key is not authorized
- [x] Update user end point successfully updates the user with valid input
- [x] Update user end point rejects unauthorized session key
- [x] Update user end point rejects invalid all fields
- [x] Deactivate user end point works successfully for authorized session key
- [x] Deactivate user rejects unauthorized session key
