### ISSUE TITLE
Accounts Page Front End

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#55]
### Description:
Create the React page for the Accounts display/editing.
### Tasks:
- [x] Create Account Reducer
- [x] Create Account Actions
- [x] Create Component to display Account Info
- [x] Create Component to Edit Account Info
### Tests:
- [x] Account info is successfully displayed
- [x] Account info can be successfully updated
- [x] Errors are displayed for invalid info (Email unavailable etc)
- [x] Account info can be successfully deactivated
