### ISSUE TITLE
Client Profile API

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#60]
### Description:
Create the end points for the client profile api.
### Tasks:
- [x] Client Profile End Point
- [x] Client Head Shot End Point
- [x] Client Allergy Sensitivity End Point
- [x] Allergy Sensitivity End Point
- [x] Client Product Preference End Point
- [x] Product Preference End Point
- [x] Client Review End Point
### Tests:
- [x] All end points work with expected parameters
- [x] All end points handle unauthorized requests
- [x] All end points handle invalid parameters
