### ISSUE TITLE
Client Profile Page

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#61]
### Description:
Create the Front End for the client profile.
### Tasks:
- [x] Client Profile Reducer
- [x] Client Profile Actions
- [x] Client Allergy Sensitivity Reducer
- [x] Client Allergy Sensitivity Actions
- [x] Client Product Preferences Reducer
- [x] Client Product Preferences Actions
- [x] Client Head Shot Reducer
- [x] Client Head Shot Actions
- [x] Client Review Reducer
- [x] Client Review Actions
- [x] Create Image Input
- [x] Create Eye Colour Input (Maybe Multi Purpose for all 3)
- [x] Create Hair Colour Input
- [x] Create Skin Tone Input
- [x] Create Client Profile Component
- [x] Display Client Profile Component
- [x] Edit Client Profile Component
### Tests:
- [x] Non-existing client profile displays appropriate message
- [x] First time user sees create client profile
- [x] Non-artist, non-owner sees only beauty bio
- [x] Artist, non-onwer and owner see full profile
- [x] Profile can be edited

**Comment by xHergz** [comment]
Just did drop downs for the eye/hair/skin tone inputs due to time being tight. Would like to have them graphical instead of just drop downs.
