### ISSUE TITLE
Instant Consultation API

### ISSUE THREAD

**Issue by kwallace0906** [xHergz/TheMakeupApp#63]
### Description:
Create the end points for instant consultation chat API 
### Tasks:
- [x] Instant Consultation End Point for initial chatroom launch
- [x] Instant Consultation End Point for live chat room

- [x] Client Review End Point
### Tests:
- [x] All end points work with expected parameters
- [x] All end points handle unauthorized requests
- [x] All end points handle invalid parameters
