### ISSUE TITLE
Artist Application Database Supporting Procedures

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#67]
### Description:
Create the supporting database procedures for artist application information.
### Tasks:
- [x] Create GetSanitizationQuizQuestionIds proc to get a list of question ids
- [x] Create GetSanitizationQuizQuestion proc to get a question by id
- [x] Create GetSanitizationQuizAnswers proc to get all answers for a question by question id
- [x] Create CreateArtistApplication proc 
- [x] Create AddExistingPortfolioLink proc 
- [x] Create AddSanitizationQuizSubmission proc
### Tests:
- [x] GetSanitizationQuizQuestionIds returns all ids
- [x] GetSanitizationQuizQuestion returns a question by id
- [x] GetSanitizationQuizQuestion returns an error for non existing id
- [x] GetSanitizationQuizAnswers returns all answer for question id
- [x] GetSanitizationQuizAnswers returns error for non existing question id
- [x] CreateArtistApplication successfully creates application entry
- [x] CreateArtistApplication returns error for non existing client profile id
- [x] AddExistingPortfolioLink successfully creates link entry
- [x] AddExistingPortfolioLink returns error for non existing application id
- [x] AddSanitizationQuizSubmission successfully creates a submission
- [x] AddSanitizationQuizSubmission returns error for non existing application id
- [x] AddSanitizationQuizSubmission returns error for non existing question id
- [x] AddSanitizationQuizSubmission returns error for non existing answer id
