### ISSUE TITLE
Sanitization Quiz API Endpoint and Artist Application API Endpoint

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#68]
### Description:
Create the API endpoint for getting the sanitation quiz data and the endpoint to create an artist application
### Tasks:
- [x] Create sanitization-quiz end point with empty get request
- [x] Create artist-application end point with empty url and body
- [x] Add support for uploading PDF/DOCX files for resumes and cover letters
- [x] Add support for database transactions because creating an application with require multiple calls to be complete
### Tests:
- [x] sanitization-quiz endpoint returns a 5 question quiz
- [x] artist-application endpoint successfully adds an application
- [x] artist-application endpoint rolls back data when encountering an error in the middle of adding an application
