### ISSUE TITLE
Artist Application Page

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#69]
### Description:
Add the artist application page for submitting new artist applications
### Tasks:
- [x] Add a link for clients on the home screen
- [x] Create Artist Application reducer
- [x] Create Artist Application actions
- [x] Create file input to select a type of file and show file name
- [x] Create list component to make a list on the client side before submitting from a textbox
- [x] Create components to display quiz
### Tests:
- [x] Page successfully renders the application with quiz
- [x] Page successfully submits an application
- [x] Page displays errors if they occur
