### ISSUE TITLE
Create User/Session Log Schema

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#7]
### Description:
Create the table to log user actions (Create, update, delete) and session actions (session created, session closed)
### Tasks:
- [x] Determine actions and columns for tables
- [x] Create User Log table
- [x] Create User Action table
- [x] Create Session Log table
- [x] Create Session Action table
- [x] Modify the CreateUser and Login procs to add log messages
### Tests:
- [x] Test by running through test cases from #6

**Comment by xHergz** [comment]
Blocked by #6 , needs User and Session tables completed.

**Comment by xHergz** [comment]
No longer blocked by #6, User and Session tables completed.

**Comment by xHergz** [comment]
Also added 2 views, Full_Session_Log and Full_User_Log for viewing the logs easier.
