### ISSUE TITLE
Artist Portfolio Database

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#73]
### Description:
Implement the database procs for the artist application page.
### Tasks:
- [x] Add the preliminary functions for the procs
- [x] Add the procs to support artist portfolios
- [x] Add the procs to support artist portfolio pictures
- [x] Add the procs to support artist qualifications
- [x] Add the procs to support artist makeover type
- [x] Add the procs to support artist services
- [x] Add the procs to support artist service addons
- [x] Add the procs to support artist service consultation
### Tests:
- [x] All procs work as expected
- [x] All procs return error codes
- [x] All procs return error codes
