### ISSUE TITLE
Artist Portfolio API

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#74]
### Description:
Create the API for artist portolio data
### Tasks:
- [x] Create the artist-portfolio endpoint
- [x] Create the artist-portfolio-picture endpoint
- [x] Create the artist-qualification endpoint
- [x] Create the artist-makeover-offered endpoint
- [x] Create the artist-service endpoint
- [x] Create the artist-service-addon endpoint
- [x] Create the artist-service-consultation endpoint
### Tests:
- [x] All endpoints return expected results
- [x] All endpoints return expected error codes
- [x] All endpoints do correct authorization
