### ISSUE TITLE
Artist Portfolio Page

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#77]
### Description:
Create the front end for the artist portfolio page.
### Tasks:
- [ ] Direct user to artist application page if not artist and has not been accepted
- [x] Create Artist Portfolio Page when user first goes to the page and has been accepted
- [x] Display profile pic and bio side by side at the top
- [x] Create 3 tabs: Portfolio, Services, About
- [x] Show Portfolio Pictures of portfolio tab
- [x] Modal to add new picture
- [x] Show services and allow editting of services of service tab
- [x] Show qualifications on about tab
### Tests:
- [x] User can successfully create artist portfolio base
- [x] User can add and remove portfolio pics
- [x] User can add and remove qualifications
- [x] User can add and remove makeover offered entries
- [x] User can add and remove services
- [x] User can add and remove service addons
- [x] User can add and remove service consultations
- [x] User can see all this info and request a service that will link them to the request form
