### ISSUE TITLE
Create Makeover Appointment Supporting DB Procedures

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#79]
### Description:
Create Makeover Appointment Supporting DB Procedures
### Tasks:
- [x] DoesMakeoverAppointmentIdExist Function
- [x] IsSessionAuthorizedForMakeoverAppointment Function
- [x] CreateMakeoverAppointment Procedure
- [x] GetMakeoverAppointment Procedure
- [x] AddMakeoverAppointmentAddon Procedure
- [x] GetMakeoverAppointmentAddons Procedure
### Tests:
- [x] DoesMakeoverAppointmentIdExist Function returns true if exists, false if not
- [x] IsSessionAuthorizedForMakeoverAppointment Function returns true if authorized, false if not
- [x] CreateMakeoverAppointment Procedure returns error codes on errors
- [x] GetMakeoverAppointment Procedure returns error if id does not exist
- [x] AddMakeoverAppointmentAddon Procedure returns error if id does not exist
- [x] GetMakeoverAppointmentAddons Procedure returns error if id does not exist
