### ISSUE TITLE
Set up the Database folder structure

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#8]
### Description:
Set up the Database folder structure to make development easier.
### Tasks:
- [x] Add scripts to root folder
  - Backup Database
  - Deploy Database
  - Drop Database
  - Restore Database
- [x] Create Error codes page on the wiki
- [x] Create sub folders
  - Data
  - Functions
  - Stored Procedures
  - Tables
  - Test Data
  - Views
