### ISSUE TITLE
Create Makeover Appointment API

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#80]
### Description:
Create Makeover Appointment API
### Tasks:
- [x] Create Makeover Appointment DAL
- [x] Add Authorization for Makeover Appointments
- [x] Create Makeover Appointment endpoint
- [x] Create Makeover Appointment Addon endpoint
### Tests:
- [x] Create makeover appointment returns error if session does not own client
- [x] Get makeover appointment returns error if session does not own client or artist
- [x] Get Addons does the same as above
