### ISSUE TITLE
Create Makeover Appointment Pages

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#81]
### Description:
Create Makeover Appointment Pages
### Tasks:
- [x] Setup Makeover Appointment Reducer
- [x] Makeover Appointment Reducer
- [x] Makeover Appointment Actions
- [x] Add button to portfolio to link to adding appointment
- [x] Add setup appointment page
- [x] Add view appointment page
### Tests:
- [x] All pages work as expected
