### ISSUE TITLE
Database Support for "Online" Artists and Artist Search

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#85]
### Description:
Create the database components to allow artists to set themselves as online, and artists to be searched by online status and geolocation.
### Tasks:
- [x] Create table for online artists
- [x] Create function to check if artist is online
- [x] Create function to calculate distance between coordinates
- [x] Create procedure to add an entry to the online artists
- [x] Create procedure to remove an entry from the online artists by artist id
- [x] Create procedure to search online artists
### Tests:
- [x] Function checks if artist portfolio id is online
- [x] Function calculates distance between coordinates
- [x] Procs successfully control online artist
- [x] Proc returns online artist within range
