### ISSUE TITLE
API for Online Artists and Search

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#86]
### Description:
Create API for Online Artists and Search
### Tasks:
- [x] Create Online Artist DAL
- [x] Create Online Artist Endpoint
- [x] GET Online Artist for search
- [x] PUT Online Artist for going online
- [x] DELETE Online Artist for going offline
### Tests:
- [x] End point checks for authorization
- [x] All end points return successfully
