### ISSUE TITLE
ASAP Makeover Search Page and Artist Dashboard

### ISSUE THREAD

**Issue by xHergz** [xHergz/TheMakeupApp#87]
### Description:
Create the Makeover Search Page
### Tasks:
- [x] Online Artist Reducer
- [x] Online Artist Actions
- [x] Add tile to homepage for Artist Dashboard
- [x] Add Artist Dashboard page with just a button for artists to go online or offline
- [x] Add ASAP Makeover Search page with dropdown for makeover type and distance
- [x] Search component shows results below: 2 tabs, list and map
### Tests:
- [x] Artist going online and offline works
- [x] Search returns results
- [x] Map shows successfully
